---
- name: Check Checkmk agent version on all hosts
  hosts: all
  gather_facts: no
  tasks:
    - name: Run checkmk agent version command
      shell: cmk -V
      register: checkmk_version_output
      ignore_errors: yes

    - name: Display Checkmk agent version
      debug:
        msg: "Checkmk agent version: {{ checkmk_version_output.stdout }}"
